app = "authoritymatch-drupal"
primary_region = "ord"

[build]
  dockerfile = "./Dockerfile"

[env]
  DRUPAL_ENV = "production"

[[mounts]]
  source = "drupal_files"
  destination = "/var/www/html/web/sites/default/files"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    interval = "15s"
    timeout = "5s"
    grace_period = "10s"
    method = "GET"
    path = "/"
    protocol = "http"

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"
